### ISSUE TITLE
Possible to disable x of y numbering?

### ISSUE THREAD

**Issue by mlolm** [jaguart/kompl#3]
Hi, this is not really a bug but more of a question. I thought it  was possible to disable the numbering in the navigation. For example 1 of 21. How can I hide that entirely?

Thanks,

**Comment by jaguart** [comment]
Hiya Malc,

Did you read through the docs - https://github.com/jaguart/kompl/blob/master/doc/example-options.md :)

If you set the DESCRIPTION option to FALSE then the description (e.g. 1 of 21) is not displayed....

```
  $kompl.play({
        ...$show,
        description: false,
      })
```

:)

**Comment by mlolm** [comment]
Hi Jeff,

Yes you're right I saw i missed that.

By the way:

1) I would like to send you something if you are in UK yet, but i know due
to corona it could be you are still in AU?
2) I have a small side project (more of a hobby really) and am building
really cool, mini, energy efficient and powerful work desktop PCs see here:
(https://hardwaare.com). Not sure if thats something you might be
interested in but I could build you one for cost if you were interested, as
a repayment, and upside for me is I could get a review (hard to generate at
early stage when you have few sales).

Cheers,
-Malcolm
ᐧ
